binning:
  abseta:
  - 0.0
  - 0.9
  - 1.2
  - 2.1
  - 2.4
  eta:
  - -2.4
  - -2.1
  - -1.2
  - -0.9
  - 0.0
  - 0.9
  - 1.2
  - 2.1
  - 2.4
  pt:
  - 20
  - 25
  - 30
  - 40
  - 50
  - 60
  - 120
  - 200
dir_name: tpTree
flags:
  medium:
    Medium: 1
    abseta:
    - 0.0
    - 2.4
    pt:
    - 10.0
    - ''
  mediumPrompt:
    Medium: 1
    abseta:
    - 0.0
    - 2.4
    dxyPVdzmin:
    - 0.0
    - 0.02
    dzPV:
    - 0.0
    - 0.1
    pt:
    - 10.0
    - ''
  tight:
    Tight2012: 1
    abseta:
    - 0.0
    - 2.4
    pt:
    - 10.0
    - ''
label: muonID
mass:
- 70.0
- 70.5
- 71.0
- 71.5
- 72.0
- 72.5
- 73.0
- 73.5
- 74.0
- 74.5
- 75.0
- 75.5
- 76.0
- 76.5
- 77.0
- 77.5
- 78.0
- 78.5
- 79.0
- 79.5
- 80.0
- 80.5
- 81.0
- 81.5
- 82.0
- 82.5
- 83.0
- 83.5
- 84.0
- 84.5
- 85.0
- 85.5
- 86.0
- 86.5
- 87.0
- 87.5
- 88.0
- 88.5
- 89.0
- 89.5
- 90.0
- 90.5
- 91.0
- 91.5
- 92.0
- 92.5
- 93.0
- 93.5
- 94.0
- 94.5
- 95.0
- 95.5
- 96.0
- 96.5
- 97.0
- 97.5
- 98.0
- 98.5
- 99.0
- 99.5
- 100.0
- 100.5
- 101.0
- 101.5
- 102.0
- 102.5
- 103.0
- 103.5
- 104.0
- 104.5
- 105.0
- 105.5
- 106.0
- 106.5
- 107.0
- 107.5
- 108.0
- 108.5
- 109.0
- 109.5
- 110.0
- 110.5
- 111.0
- 111.5
- 112.0
- 112.5
- 113.0
- 113.5
- 114.0
- 114.5
- 115.0
- 115.5
- 116.0
- 116.5
- 117.0
- 117.5
- 118.0
- 118.5
- 119.0
- 119.5
- 120.0
- 120.5
- 121.0
- 121.5
- 122.0
- 122.5
- 123.0
- 123.5
- 124.0
- 124.5
- 125.0
- 125.5
- 126.0
- 126.5
- 127.0
- 127.5
- 128.0
- 128.5
- 129.0
- 129.5
- 130.0
observable:
- pt
- abseta
- eta
observable2D:
  abseta: pt
  eta: pt
pdfs:
  voigtPlusExpo:
  - mass[90,70,130]
  - Voigtian::signalPass(mass, mean1p[90,80,100], width1p[2.495], sigma1p[3,1,20])
  - Voigtian::signalFail(mass, mean1f[90,80,100], width1f[3,1,2], sigma1f[3,0,20])
  - Exponential::backgroundPass(mass, lp[0,-10,10])
  - Exponential::backgroundFail(mass, lf[0,-10,10])
  - efficiency[0.9,0,1]
  - signalFractionInPassing[0.9]
  vpvPlusCMS:
  - mass[90,70,130]
  - Voigtian::signal1(mass, mean1[90,80,100], width[2.495], sigma1[2,1,3])
  - Voigtian::signal2(mass, mean2[90,80,100], width,        sigma2[4,3,10])
  - SUM::signalPass(vPropp[0.8,0,1]*signal1,signal2)
  - Voigtian::theSig1f(mass, mean2f[90,80,100], width2f[3,1,2], sigma2f[2,1,3])
  - Voigtian::theSig2f(mass, mean2f[90,80,100], width2f, sigma2f2[4,2,10])
  - SUM::signalFail(vPropf[0.8,0,1]*theSig1f,theSig2f)
  - RooCMSShape::backgroundPass(mass, alphaPass[70.,60.,90.], betaPass[0.02, 0.01,0.1],
    gammaPass[0.001, 0.,0.1], peakPass[90.0])
  - RooCMSShape::backgroundFail(mass, alphaFail[70.,60.,90.], betaFail[0.02, 0.01,0.1],
    gammaFail[0.001, 0.,0.1], peakPass)
  - efficiency[0.9,0.7,1]
  - signalFractionInPassing[0.9]
  vpvPlusCMSbeta0p2:
  - mass[90,70,130]
  - Voigtian::signal1(mass, mean1[90,80,100], width[2.495], sigma1[2,1,3])
  - Voigtian::signal2(mass, mean2[90,80,100], width,        sigma2[4,3,10])
  - RooCMSShape::backgroundPass(mass, alphaPass[70.,60.,90.], betaPass[0.001, 0.,0.1],
    gammaPass[0.001, 0.,0.1], peakPass[90.0])
  - RooCMSShape::backgroundFail(mass, alphaFail[70.,60.,90.], betaFail[0.03, 0.02,0.1],
    gammaFail[0.001, 0.,0.1], peakPass)
  - SUM::signalPass(vPropp[0.8,0,1]*signal1,signal2)
  - Voigtian::theSig1f(mass, mean2f[90,80,100], width2f[3,1,2], sigma2f[2,1,3])
  - Voigtian::theSig2f(mass, mean2f[90,80,100], width2f, sigma2f2[4,2,10])
  - SUM::signalFail(vPropf[0.8,0,1]*theSig1f,theSig2f)
  - efficiency[0.9,0.7,1]
  - signalFractionInPassing[0.9]
  vpvPlusCheb:
  - mass[90,70,130]
  - Voigtian::signal1(mass, mean1[90,80,100], width[2.495], sigma1[2,1,3])
  - Voigtian::signal2(mass, mean2[90,80,100], width,        sigma2[4,3,10])
  - SUM::signalPass(vPropp[0.8,0,1]*signal1,signal2)
  - Voigtian::theSig1f(mass, mean2f[90,80,100], width2f[3,1,2], sigma2f[2,1,3])
  - Voigtian::theSig2f(mass, mean2f[90,80,100], width2f, sigma2f2[4,2,10])
  - SUM::signalFail(vPropf[0.8,0,1]*theSig1f,theSig2f)
  - RooChebychev::backgroundPass(mass, {a0[0.25,0,0.5], a1[-0.25,-1,0.1],a2[0.,-0.25,0.25]})
  - RooChebychev::backgroundFail(mass, {a0[0.25,0,0.5], a1[-0.25,-1,0.1],a2[0.,-0.25,0.25]})
  - efficiency[0.9,0.7,1]
  - signalFractionInPassing[0.9]
  vpvPlusExpo:
  - mass[90,70,130]
  - Voigtian::signal1(mass, mean1[90,80,100], width[2.495], sigma1[2,1,3])
  - Voigtian::signal2(mass, mean2[90,80,100], width,        sigma2[4,2,10])
  - SUM::signalPass(vPropp[0.8,0,1]*signal1,signal2)
  - Voigtian::theSig1f(mass, mean2f[90,80,100], width2f[3,1,2], sigma2f[2,1,3])
  - Voigtian::theSig2f(mass, mean2f[90,80,100], width2f, sigma2f2[4,2,10])
  - SUM::signalFail(vPropf[0.8,0,1]*theSig1f,theSig2f)
  - Exponential::backgroundPass(mass, lp[-0.1,-1,0.1])
  - Exponential::backgroundFail(mass, lf[-0.1,-1,0.1])
  - efficiency[0.9,0,1]
  - signalFractionInPassing[0.9]
  vpvPlusExpoMin70:
  - mass[90,70,130]
  - Voigtian::signal1(mass, mean1[90,80,100], width[2.495], sigma1[2,1,3])
  - Voigtian::signal2(mass, mean2[90,80,100], width,        sigma2[4,3,10])
  - SUM::signalPass(vPropp[0.8,0,1]*signal1,signal2)
  - Voigtian::theSig1f(mass, mean2f[90,80,100], width2f[3,1,2], sigma2f[2,1,3])
  - Voigtian::theSig2f(mass, mean2f[90,80,100], width2f, sigma2f2[4,2,10])
  - SUM::signalFail(vPropf[0.8,0,1]*theSig1f,theSig2f)
  - Exponential::backgroundPass(mass, lp[-0.1,-1,0.1])
  - Exponential::backgroundFail(mass, lf[-0.1,-1,0.1])
  - efficiency[0.9,0.7,1]
  - signalFractionInPassing[0.9]
sample:
- DY
- RunF
- RunE
- RunB
- RunC
- RunD
- RunG
- RunH
tag_selection:
  mass:
  - 70.0
  - 130
  pair_deltaR:
  - 0.4
  - ''
  pair_probeMultiplicity: 1
  tag_IsoMu27: 1
  tag_abseta:
  - 0.0
  - 2.4
  tag_combRelIsoPF04:
  - 0.0
  - 0.15
  tag_dxyPVdzmin:
  - 0.0
  - 0.2
  tag_dzPV:
  - 0.0
  - 0.5
  tag_glbChi2:
  - 0.0
  - 10.0
  tag_glbValidMuHits:
  - 0
  - ''
  tag_numberOfMatchedStations:
  - 1
  - ''
  tag_pt:
  - 29.0
  - ''
  tag_tkTrackerLay:
  - 5
  - ''
  tag_tkValidPixelHits:
  - 0
  - ''
tree_name: fitter_tree
year: 2016
